config/routes.rb
RssReader::Application.routes.draw do
  resources :feeds do
    resources :articles do
      member do
        post :mark_read
        post :mark_unread
        post :toggle_saved
      end
    end
    collection do
      post :refresh
      post :mark_all_read
    end
  end
  match "/saved" => "users#saved"
  devise_for :users
  root :to => 'feeds#index'

end

app/views/layouts/_messages.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert <%= flash_class(level) %>">
      <button type="button" class="close" data-dismiss="alert">&times;</button> 
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "RSS Reader", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
    <li>
      <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <li>
      <%= link_to 'Saved', '/saved' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>

<a data-target="#subscription-modal" role="button" class="btn" data-toggle="modal">Subscribe</a>
<ul>
  <% current_user.feeds.each do |feed| %>
    <li><%= link_to feed.name, feed_path(feed) %></li>
  <% end %>
</ul>
<%= render :partial => "shared/subscribe_modal" %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RSS Reader" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container-fluid">
        <div class='row-fluid'>
          <div class='span2 sidenav'>
            <div class="row">
              <div class='span10 offset1'>
                <h3><%= yield :title %></h3>
              </div>
            </div>
            <%= render 'layouts/sidebar' %>
          </div>
          <div class='span10'>
            <%= render 'layouts/messages'%>
            <div class="btn-group">
              <button class='btn btn-small refresh'>Refresh</button>
              <button class="btn btn-small mark-all-read">Mark all as read</button>
            </div>
            <div class="btn-group">
              <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
                New Items
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#">All Items</a></li>
                <li><a href="#">New Items</a>
              </ul>
            </div>
            <div class="scrolling">
                <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>

    <%= javascript_include_tag "application" %>
</html>